<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <AssemblyName>LoadingIndicators.WPF</AssemblyName>
    <Title>LoadingIndicators.WPF</Title>
    <RootNamespace>LoadingIndicators.WPF</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Link="README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Link="LICENSE.txt" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
